### ISSUE TITLE
No refresh graph

### ISSUE THREAD

**Issue by beigirad** [aeab13/Gitnuro#4]
I push my branch in remote by terminal. 

And then I go back to Gitnuro. It wasn't updated its graph.

I think it needs a refresh button on top or check branches state when app gets user focus.

**Comment by aeab13** [comment]
Hey! 
Thanks for you interest. This week I'm working in a refactor of the files watcher to improve the detection of changes, even in the git directory. I'll also add the option to force a refresh of the repository in the UI just in case this refactor doesn't cover all the cases.

**Comment by aeab13** [comment]
Sorry for the delay. The latest commits detects changes in the .git dir and automatically refreshes the repository state. Just in case, as mentioned in my previous comment, an option to refresh the repository has been added in the additional options of each repository.
